version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: users-crud-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
      - MONGO_INITDB_DATABASE=users_crud
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
